language: python

python: 
- 3.6

# whitelist
branches:
  only:
    - master
    - develop

install:
- pip install -r requirements.txt
- pip install coveralls

script:
- pytest
- coverage run --source=app -m pytest && coverage report

after_success:
- coveralls