language: "python"

python: 
- "3.6"

install:
- "pip install -r requirements.txt"
- "pip install coveralls"

# command to install dependencies
script: python backend/app.py
branches:
  only:
    - develop